"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { PortalHeader } from "@/components/PortalHeader";
import { ApiError, ApiUser, apiFetch, authApi, errorMessage } from "@/lib/auth-api";

type Permission={id:string;slug:string;name:string;group:string};
type Role={id:string;name:string;slug:string;description?:string;scope:string;system:boolean;permissions:Permission[]};

export default function AdminPage(){
  const router=useRouter(); const [me,setMe]=useState<ApiUser|null>(null); const [users,setUsers]=useState<ApiUser[]>([]); const [roles,setRoles]=useState<Role[]>([]); const [permissions,setPermissions]=useState<Permission[]>([]); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [needs2fa,setNeeds2fa]=useState(false); const [busy,setBusy]=useState(false); const [roleName,setRoleName]=useState(""); const [selectedPermissions,setSelectedPermissions]=useState<string[]>([]); const [selectedUser,setSelectedUser]=useState(""); const [selectedRole,setSelectedRole]=useState("");
  const load=useCallback(async()=>{try{const current=await authApi.me();setMe(current.data);if(!current.data.permissions.includes("identity.admin.access")){setError("This account does not have platform administration permission.");return}const [u,r]=await Promise.all([apiFetch<{data:ApiUser[]}>("/api/v1/admin/users"),apiFetch<{data:Role[];permissions:Permission[]}>("/api/v1/admin/roles")]);setUsers(u.data);setRoles(r.data);setPermissions(r.permissions);setNeeds2fa(false)}catch(e){if(e instanceof ApiError&&e.code==="ADMIN_TWO_FACTOR_REQUIRED"){setNeeds2fa(true);setError("Enable two-factor authentication before using administration.")}else if((e as {status?:number}).status===401)router.replace("/login");else setError(errorMessage(e))}},[router]);
  useEffect(()=>{void load()},[load]);
  async function changeStatus(user:ApiUser,status:string){const reason=window.prompt(`Reason for changing ${user.email} to ${status}:`);if(!reason)return;setBusy(true);setError("");try{await apiFetch(`/api/v1/admin/users/${user.id}/status`,{method:"PATCH",body:JSON.stringify({status,reason})});setMessage("Account status updated.");await load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
  async function createRole(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{await apiFetch("/api/v1/admin/roles",{method:"POST",body:JSON.stringify({name:roleName,permissions:selectedPermissions})});setRoleName("");setSelectedPermissions([]);setMessage("Tenant role created.");await load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
  async function assignRole(event:FormEvent){event.preventDefault();if(!selectedUser||!selectedRole)return;setBusy(true);setError("");try{await apiFetch(`/api/v1/admin/users/${selectedUser}/roles/${selectedRole}`,{method:"POST"});setMessage("Role assigned.");await load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
  if(!me&&!error)return <main className="centerPage"><div className="loader"/><p>Loading administrative controls…</p></main>;
  return <main className="portal"><PortalHeader name={me?.name} admin/><section className="shell portalTitle"><p className="eyebrow">Protected administration</p><h1>Identity administration</h1><p>Customer access, account status and tenant roles are controlled here.</p><div className="actions"><Link className="secondary" href="/admin/wallets">Open wallet administration</Link><Link className="secondary" href="/admin/commerce">Commerce administration</Link><Link className="secondary" href="/admin/suppliers">Supplier engine</Link><Link className="secondary" href="/admin/rules">Rules & fraud</Link><Link className="secondary" href="/admin/saas">SaaS & plugins</Link><Link className="secondary" href="/admin/analytics">AI & analytics</Link><Link className="secondary" href="/admin/payments">Payments & reconciliation</Link><Link className="secondary" href="/admin/reports">Reports & invoices</Link></div></section>{error?<div className="shell notice error">{error}{needs2fa?<div><Link className="primary inlineCta" href="/security">Enable 2FA</Link></div>:null}</div>:null}{message?<div className="shell notice success">{message}</div>:null}{!error||users.length?<section className="shell adminLayout">
    <article className="adminCard wide"><div className="cardHead"><div><small>Directory</small><h2>Tenant users</h2></div><span className="pill">{users.length} users</span></div><div className="tableWrap"><table><thead><tr><th>User</th><th>Verification</th><th>Roles</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.name}</strong><small>{u.email}</small></td><td>{u.email_verified?"Verified":"Pending"}</td><td>{u.roles.map(r=>r.name).join(", ")}</td><td><span className={u.status==="active"?"pill good":"pill warn"}>{u.status}</span></td><td><div className="rowActions"><button disabled={busy||u.id===me?.id} onClick={()=>changeStatus(u,u.status==="active"?"suspended":"active")}>{u.status==="active"?"Suspend":"Activate"}</button></div></td></tr>)}</tbody></table></div></article>
    <article className="adminCard"><div className="cardHead"><div><small>Authorization</small><h2>Create tenant role</h2></div></div><form className="formStack compact" onSubmit={createRole}><label>Role name<input value={roleName} onChange={(e)=>setRoleName(e.target.value)} required /></label><div className="permissionPicker">{permissions.map(p=><label className="check" key={p.id}><input type="checkbox" checked={selectedPermissions.includes(p.id)} onChange={(e)=>setSelectedPermissions(current=>e.target.checked?[...current,p.id]:current.filter(id=>id!==p.id))}/><span><strong>{p.name}</strong><small>{p.slug}</small></span></label>)}</div><button className="primary" disabled={busy}>Create role</button></form></article>
    <article className="adminCard"><div className="cardHead"><div><small>Assignment</small><h2>Assign a role</h2></div></div><form className="formStack compact" onSubmit={assignRole}><label>User<select value={selectedUser} onChange={(e)=>setSelectedUser(e.target.value)} required><option value="">Select user</option>{users.map(u=><option key={u.id} value={u.id}>{u.name} · {u.email}</option>)}</select></label><label>Role<select value={selectedRole} onChange={(e)=>setSelectedRole(e.target.value)} required><option value="">Select role</option>{roles.filter(r=>r.slug!=="platform-super-admin").map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><button className="primary" disabled={busy}>Assign role</button></form><div className="roleList">{roles.map(r=><div key={r.id}><strong>{r.name}</strong><small>{r.scope} · {r.permissions.length} permissions</small></div>)}</div></article>
  </section>:null}</main>;
}
