<?php

return [
    'external_delivery_enabled' => (bool) env('AGCP_EXTERNAL_DELIVERY_ENABLED', false),
    'version' => '2026-2027-master',
    'architecture' => 'modular-monolith-event-driven',

    'modules' => [
        'Platform',
        'Tenancy',
        'Identity',
        'Licensing',
        'Gateway',
        'Wallet',
        'Catalog',
        'Inventory',
        'Checkout',
        'Orders',
        'Supplier',
        'Payments',
        'Pricing',
        'Fraud',
        'SaaS',
        'Plugins',
        'Automation',
        'Analytics',
        'Marketplace',
        'Mobile',
        'AI',
        'Notifications',
        'Support',
        'Reporting',
        'Reliability',
    ],

    'transactional_core' => [
        'Tenancy',
        'Identity',
        'Wallet',
        'Catalog',
        'Inventory',
        'Checkout',
        'Orders',
        'Supplier',
        'Payments',
    ],

    'integration_patterns' => [
        'supplier_provider_adapter',
        'dhru_compatible_adapter',
        'payment_provider_adapter',
        'idempotency_key',
        'transactional_outbox',
    ],

    'principles' => [
        'tenant-aware',
        'least-privilege',
        'idempotent-money-and-order-mutations',
        'double-entry-ledger',
        'outbox-first-integration-events',
        'observable-background-jobs',
        'provider-adapter-boundaries',
        'api-versioning',
        'ai-governed-not-autonomous-by-default',
        'self-hosted-and-cloud-entitlement-ready',
    ],
];