"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { PortalHeader } from "@/components/PortalHeader";
import { ApiUser, authApi, errorMessage } from "@/lib/auth-api";
import { PaymentIntent, PaymentProvider, paymentsApi } from "@/lib/payments-api";
import { Wallet, walletApi } from "@/lib/wallet-api";

function money(value:number,currency:string){return new Intl.NumberFormat("en-US",{style:"currency",currency}).format(value/100)}
export default function PaymentsPage(){
 const router=useRouter();const[user,setUser]=useState<ApiUser|null>(null);const[wallets,setWallets]=useState<Wallet[]>([]);const[providers,setProviders]=useState<PaymentProvider[]>([]);const[intents,setIntents]=useState<PaymentIntent[]>([]);const[walletId,setWalletId]=useState("");const[providerCode,setProviderCode]=useState("");const[amount,setAmount]=useState("10.00");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
 async function load(){try{const[u,w,p,i]=await Promise.all([authApi.me(),walletApi.wallets(),paymentsApi.providers(),paymentsApi.intents()]);setUser(u.data);setWallets(w.data);setProviders(p.data);setIntents(i.data);if(!walletId&&w.data[0])setWalletId(w.data[0].id);if(!providerCode&&p.data[0])setProviderCode(p.data[0].code)}catch(e){if((e as {status?:number}).status===401)router.replace("/login");else setMessage(errorMessage(e))}}
 useEffect(()=>{void load()},[]);
 const wallet=useMemo(()=>wallets.find(item=>item.id===walletId),[wallets,walletId]);
 async function create(event:FormEvent){event.preventDefault();if(!wallet)return;setBusy(true);setMessage("");try{const result=await paymentsApi.create({wallet_id:wallet.id,provider_code:providerCode,amount,currency:wallet.currency});setMessage(`Payment ${result.data.reference} created. Complete the verified provider flow before balance is credited.`);await load()}catch(e){setMessage(errorMessage(e))}finally{setBusy(false)}}
 async function simulate(intent:PaymentIntent){setBusy(true);try{await paymentsApi.simulate(intent.id);setMessage("Sandbox webhook verified and wallet credit posted.");await load()}catch(e){setMessage(errorMessage(e))}finally{setBusy(false)}}
 async function cancel(intent:PaymentIntent){setBusy(true);try{await paymentsApi.cancel(intent.id);setMessage("Payment intent cancelled.");await load()}catch(e){setMessage(errorMessage(e))}finally{setBusy(false)}}
 if(!user&&!message)return <main className="centerPage"><div className="loader"/><p>Loading secure payments…</p></main>;
 return <main className="portal"><PortalHeader name={user?.name}/><section className="shell portalTitle"><p className="eyebrow">Phase 9 · Payment orchestration</p><h1>Add balance through verified payment events</h1><p>Creating an intent never credits your wallet. Balance moves only after a signed provider webhook is accepted and reconciled.</p></section>{message?<div className="shell notice success">{message}</div>:null}<section className="shell adminLayout"><article className="adminCard"><div className="cardHead"><div><small>New payment</small><h2>Create an add-balance intent</h2></div></div><form className="formStack compact" onSubmit={create}><label>Wallet<select value={walletId} onChange={e=>setWalletId(e.target.value)} required>{wallets.map(item=><option key={item.id} value={item.id}>{item.currency} · available {item.available}</option>)}</select></label><label>Provider<select value={providerCode} onChange={e=>setProviderCode(e.target.value)} required>{providers.map(item=><option key={item.id} value={item.code}>{item.name} · {item.mode}</option>)}</select></label><label>Credit amount<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" required/></label><button className="primary" disabled={busy||!walletId||!providerCode}>{busy?"Working…":"Create payment intent"}</button></form></article><article className="adminCard wide"><div className="cardHead"><div><small>Payment history</small><h2>{intents.length} recent intents</h2></div><span className="pill">Webhook-only credit</span></div><div className="tableWrap"><table><thead><tr><th>Reference</th><th>Provider</th><th>Credit</th><th>Total charged</th><th>Status</th><th>Action</th></tr></thead><tbody>{intents.map(intent=><tr key={intent.id}><td><strong>{intent.reference}</strong><small>{intent.created_at?.slice(0,19).replace("T"," ")}</small></td><td>{intent.provider?.name??"Unknown"}</td><td>{money(intent.amount_minor,intent.currency)}</td><td>{money(intent.total_minor,intent.currency)}<small>{intent.fee_minor?`${money(intent.fee_minor,intent.currency)} fee`:"No fee"}</small></td><td><span className={intent.status==="completed"?"pill good":intent.status==="failed"?"pill warn":"pill"}>{intent.status}</span></td><td><div className="rowActions">{intent.status==="pending"&&intent.provider?.provider==="sandbox"?<button disabled={busy} onClick={()=>simulate(intent)}>Complete sandbox</button>:null}{["created","pending"].includes(intent.status)?<button disabled={busy} onClick={()=>cancel(intent)}>Cancel</button>:null}</div></td></tr>)}{intents.length===0?<tr><td colSpan={6}>No payment intent yet.</td></tr>:null}</tbody></table></div></article></section></main>;
}
