"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { PortalHeader } from "@/components/PortalHeader";
import { ApiUser, authApi, errorMessage } from "@/lib/auth-api";
import { Cart, commerceApi } from "@/lib/commerce-api";
import { Wallet, walletApi } from "@/lib/wallet-api";
export default function CartPage(){
 const router=useRouter();const [user,setUser]=useState<ApiUser|null>(null);const [cart,setCart]=useState<Cart|null>(null);const [wallets,setWallets]=useState<Wallet[]>([]);const [walletId,setWalletId]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 async function load(){const [u,c,w]=await Promise.all([authApi.me(),commerceApi.cart(),walletApi.wallets()]);setUser(u.data);setCart(c.data);setWallets(w.data);setWalletId(current=>current||w.data.find(x=>x.currency===c.data.currency)?.id||"")}
 useEffect(()=>{load().catch(e=>{if((e as {status?:number}).status===401)router.replace("/login");else setMessage(errorMessage(e))})},[router]);
 async function update(id:string,quantity:number){try{setCart((await commerceApi.updateCartItem(id,quantity)).data)}catch(e){setMessage(errorMessage(e))}}
 async function checkout(){if(!cart||!walletId)return;setBusy(true);setMessage("");try{const result=await commerceApi.checkout(cart.id,walletId);router.push(`/orders?placed=${result.data.number}`)}catch(e){setMessage(errorMessage(e))}finally{setBusy(false)}}
 if(!user||!cart)return <main className="centerPage"><div className="loader"/><p>{message||"Loading cart…"}</p></main>;
 return <main className="portal"><PortalHeader name={user.name} admin={user.permissions.includes("identity.admin.access")}/><section className="shell portalTitle"><p className="eyebrow">Secure checkout</p><h1>Your cart</h1><p>Prices are recalculated and inventory is reserved atomically during checkout.</p></section>{message?<div className="shell notice error">{message}</div>:null}<section className="shell twoColumn"><article className="adminCard"><div className="cardHead"><div><small>Items</small><h2>{cart.items.length} cart lines</h2></div><span className="pill">{cart.subtotal} {cart.currency}</span></div>{cart.items.length?<div className="cartList">{cart.items.map(line=><div className="cartLine" key={line.id}><div><strong>{line.variant.item.name}</strong><small>{line.variant.name} · {line.variant.sku}</small></div><div className="quantity"><button onClick={()=>update(line.id,line.quantity-1)}>−</button><span>{line.quantity}</span><button onClick={()=>update(line.id,line.quantity+1)}>+</button></div><strong>{(line.total_minor/100).toFixed(2)} {cart.currency}</strong></div>)}</div>:<div className="emptyState"><p>Your cart is empty.</p><Link className="primary" href="/catalog">Browse catalog</Link></div>}</article><article className="adminCard"><div className="cardHead"><div><small>Wallet payment</small><h2>Order summary</h2></div></div><div className="summaryRows"><div><span>Subtotal</span><strong>{cart.subtotal} {cart.currency}</strong></div><div><span>Total</span><strong>{cart.subtotal} {cart.currency}</strong></div></div><label className="serviceField">Payment wallet<select value={walletId} onChange={e=>setWalletId(e.target.value)}><option value="">Select wallet</option>{wallets.filter(w=>w.currency===cart.currency).map(w=><option key={w.id} value={w.id}>{w.type} · {w.available} {w.currency}</option>)}</select></label><button className="primary full" disabled={busy||!walletId||cart.items.length===0} onClick={checkout}>{busy?"Placing order…":"Pay from wallet"}</button><p className="finePrint">A successful checkout creates an immutable ledger debit and a commerce revenue credit.</p></article></section></main>
}
