<?php
namespace Modules\Reporting\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use Carbon\CarbonImmutable;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;
use Modules\Commerce\Infrastructure\Models\Order;
use Modules\Reporting\Application\Services\DataExportService;
use Modules\Reporting\Application\Services\InvoiceDocumentService;
use Modules\Reporting\Application\Services\InvoiceService;
use Modules\Reporting\Application\Services\ReportingDashboardService;
use Modules\Reporting\Application\Services\ReportScheduleService;
use Modules\Reporting\Http\Resources\InvoiceResource;
use Modules\Reporting\Infrastructure\Models\DataExport;
use Modules\Reporting\Infrastructure\Models\Invoice;
use Modules\Reporting\Infrastructure\Models\ReportSchedule;
use Modules\Reporting\Infrastructure\Models\TaxRate;
use Modules\Reporting\Infrastructure\Models\TenantTaxProfile;
use Modules\Tenancy\Application\TenantContext;
final class AdminReportingController extends Controller
{
    public function index(Request $request,TenantContext $context,ReportingDashboardService $dashboard):array{$data=$request->validate(['start'=>['nullable','date'],'end'=>['nullable','date','after_or_equal:start']]);$start=!empty($data['start'])?CarbonImmutable::parse($data['start'])->startOfDay():null;$end=!empty($data['end'])?CarbonImmutable::parse($data['end'])->endOfDay():null;return ['data'=>$dashboard->build($context->requireId(),$start,$end)];}
    public function generateInvoice(TenantContext $context,Order $order,InvoiceService $service):array{abort_unless($order->tenant_id===$context->requireId(),404);return ['data'=>(new InvoiceResource($service->generate($order,request()->user())))->resolve()];}
    public function voidInvoice(Request $request,TenantContext $context,Invoice $invoice,InvoiceService $service):array{abort_unless($invoice->tenant_id===$context->requireId(),404);$data=$request->validate(['reason'=>['required','string','max:500']]);return ['data'=>(new InvoiceResource($service->void($invoice,$request->user(),$data['reason'])))->resolve()];}
    public function invoiceDocument(TenantContext $context,Invoice $invoice,InvoiceDocumentService $documents){abort_unless($invoice->tenant_id===$context->requireId(),404);return response($documents->html($invoice),200,['Content-Type'=>'text/html; charset=UTF-8','Content-Disposition'=>'inline; filename="'.$invoice->number.'.html"']);}
    public function updateTaxProfile(Request $request,TenantContext $context):array{$data=$request->validate(['legal_name'=>['required','string','max:190'],'tax_registration_number'=>['nullable','string','max:120'],'country_code'=>['nullable','string','size:2'],'region_code'=>['nullable','string','max:80'],'invoice_prefix'=>['required','alpha_dash','max:20'],'default_tax_behavior'=>['required',Rule::in(['inclusive','exclusive'])],'address'=>['nullable','array'],'invoice_footer'=>['nullable','string','max:2000'],'status'=>['nullable',Rule::in(['active','inactive'])]]);if(isset($data['country_code']))$data['country_code']=strtoupper($data['country_code']);$profile=TenantTaxProfile::query()->firstOrNew(['tenant_id'=>$context->requireId()]);if(!$profile->exists)$profile->next_invoice_sequence=1;$profile->fill($data);$profile->save();return ['data'=>$profile];}
    public function storeTaxRate(Request $request,TenantContext $context):array{$tenantId=$context->requireId();$data=$this->rateData($request,$tenantId);return ['data'=>TaxRate::query()->create(['tenant_id'=>$tenantId]+$data)];}
    public function updateTaxRate(Request $request,TenantContext $context,TaxRate $taxRate):array{abort_unless($taxRate->tenant_id===$context->requireId(),404);$taxRate->update($this->rateData($request,$taxRate->tenant_id,$taxRate->id,true));return ['data'=>$taxRate->fresh()];}
    public function createExport(Request $request,TenantContext $context,DataExportService $service):array{$data=$request->validate(['type'=>['required',Rule::in(DataExportService::TYPES)],'start'=>['nullable','date'],'end'=>['nullable','date','after_or_equal:start'],'filters'=>['nullable','array']]);return ['data'=>$service->create($context->requireId(),$data['type'],$request->user(),$data['start']??null,$data['end']??null,$data['filters']??[])];}
    public function downloadExport(TenantContext $context,DataExport $dataExport){abort_unless($dataExport->tenant_id===$context->requireId()&&$dataExport->storage_path,404);abort_unless(Storage::disk($dataExport->storage_disk)->exists($dataExport->storage_path),404);return Storage::disk($dataExport->storage_disk)->download($dataExport->storage_path,'agcp-'.$dataExport->type.'-'.$dataExport->id.'.csv',['X-Checksum-SHA256'=>$dataExport->checksum_sha256]);}
    public function storeSchedule(Request $request,TenantContext $context,ReportScheduleService $service):array{$data=$request->validate(['name'=>['required','string','max:160'],'report_type'=>['required',Rule::in(DataExportService::TYPES)],'frequency'=>['required',Rule::in(['daily','weekly','monthly'])],'timezone'=>['required','timezone'],'recipients'=>['nullable','array'],'recipients.*'=>['email'],'filters'=>['nullable','array'],'enabled'=>['nullable','boolean']]);$schedule=ReportSchedule::query()->create(['tenant_id'=>$context->requireId(),'created_by'=>$request->user()->id]+$data+['enabled'=>$data['enabled']??true,'next_run_at'=>$service->next($data['frequency'],CarbonImmutable::now($data['timezone']))->utc()]);return ['data'=>$schedule];}
    public function updateSchedule(Request $request,TenantContext $context,ReportSchedule $schedule,ReportScheduleService $service):array{abort_unless($schedule->tenant_id===$context->requireId(),404);$data=$request->validate(['name'=>['sometimes','string','max:160'],'frequency'=>['sometimes',Rule::in(['daily','weekly','monthly'])],'timezone'=>['sometimes','timezone'],'recipients'=>['sometimes','array'],'recipients.*'=>['email'],'filters'=>['sometimes','array'],'enabled'=>['sometimes','boolean']]);$schedule->update($data);if(isset($data['frequency'])||isset($data['timezone']))$schedule->update(['next_run_at'=>$service->next($schedule->frequency,CarbonImmutable::now($schedule->timezone))->utc()]);return ['data'=>$schedule->fresh()];}
    public function runSchedule(TenantContext $context,ReportSchedule $schedule,ReportScheduleService $service):array{abort_unless($schedule->tenant_id===$context->requireId(),404);return ['data'=>$service->run($schedule,request()->user())];}
    private function rateData(Request $request,string $tenantId,?string $ignore=null,bool $partial=false):array{$rules=['code'=>[$partial?'sometimes':'required','alpha_dash','max:80',Rule::unique('tax_rates','code')->where('tenant_id',$tenantId)->ignore($ignore)],'name'=>[$partial?'sometimes':'required','string','max:160'],'jurisdiction'=>['nullable','string','max:160'],'country_code'=>['nullable','string','size:2'],'region_code'=>['nullable','string','max:80'],'rate_basis_points'=>[$partial?'sometimes':'required','integer','min:0','max:100000'],'price_inclusive'=>[$partial?'sometimes':'required','boolean'],'applies_to'=>[$partial?'sometimes':'required',Rule::in(['all','physical','digital','service'])],'status'=>['nullable',Rule::in(['active','inactive'])],'valid_from'=>['nullable','date'],'valid_until'=>['nullable','date','after:valid_from']];$data=$request->validate($rules);if(isset($data['country_code']))$data['country_code']=strtoupper($data['country_code']);return $data;}
}
