"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { PortalHeader } from "@/components/PortalHeader";
import { ApiUser, authApi, errorMessage } from "@/lib/auth-api";
import { AiInsight, AnalyticsDashboard, analyticsApi } from "@/lib/analytics-api";

function money(value:number,currency="USD"){return new Intl.NumberFormat("en-US",{style:"currency",currency}).format(value/100)}
function label(value:string){return value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}

export default function AnalyticsAdminPage(){
 const[user,setUser]=useState<ApiUser|null>(null);const[data,setData]=useState<AnalyticsDashboard|null>(null);const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
 async function load(){try{const[u,d]=await Promise.all([authApi.me(),analyticsApi.dashboard()]);setUser(u.data);setData(d.data)}catch(e){setMessage(errorMessage(e))}}
 useEffect(()=>{void load()},[]);
 async function refresh(){setBusy(true);setMessage("");try{const result=await analyticsApi.refresh({window_days:30,horizon_days:14});setMessage(`Analytics refresh completed${result.data.run_id?` · run ${result.data.run_id.slice(0,8)}`:""}.`);await load()}catch(e){setMessage(errorMessage(e))}finally{setBusy(false)}}
 async function dismiss(insight:AiInsight){setBusy(true);try{await analyticsApi.updateInsight(insight.id,"dismissed");setMessage("Insight dismissed.");await load()}catch(e){setMessage(errorMessage(e))}finally{setBusy(false)}}
 const snapshot=data?.snapshot;const forecast=data?.forecast;const currency=snapshot?.currency??forecast?.currency??"USD";
 const totalSegments=useMemo(()=>Object.values(data?.segment_summary??{}).reduce((sum,count)=>sum+count,0),[data]);
 if(!user&&!message)return <main className="centerPage"><div className="loader"/><p>Loading analytics control center…</p></main>;
 return <main className="portal"><PortalHeader name={user?.name} admin/><section className="shell portalTitle"><p className="eyebrow">Phase 8 · Explainable AI & analytics</p><h1>Decisions backed by auditable evidence</h1><p>Refresh revenue KPIs, deterministic forecasts, customer segments, supplier recommendations and AI-assisted operational insights without sending tenant data to an external model.</p><div className="actions"><button className="primary" disabled={busy} onClick={refresh}>{busy?"Refreshing…":"Refresh analytics"}</button><Link className="secondary" href="/admin/rules">Rules & risk</Link><Link className="secondary" href="/admin/suppliers">Supplier engine</Link></div></section>{message?<div className="shell notice success">{message}</div>:null}
 {!snapshot?<section className="shell emptyState"><h2>No analytics snapshot yet</h2><p>Run the first refresh to calculate the last 30 days and create a 14-day forecast.</p><button className="primary" disabled={busy} onClick={refresh}>Run first refresh</button></section>:<>
 <section className="shell metricGrid"><article><small>Net revenue</small><strong>{money(snapshot.net_revenue_minor,currency)}</strong><span>{snapshot.period_start} → {snapshot.period_end}</span></article><article><small>Orders</small><strong>{snapshot.orders_count}</strong><span>{snapshot.completed_orders_count} completed</span></article><article><small>Customers</small><strong>{snapshot.unique_customers}</strong><span>{money(snapshot.average_order_value_minor,currency)} average order</span></article><article><small>Supplier success</small><strong>{Number(snapshot.supplier_success_rate).toFixed(1)}%</strong><span>{snapshot.risk_review_count} risk reviews</span></article></section>
 <section className="shell adminLayout"><article className="adminCard wide"><div className="cardHead"><div><small>Revenue forecast</small><h2>{forecast?`${money(forecast.predicted_revenue_minor,currency)} over ${forecast.horizon_days} days`:"Not generated"}</h2></div>{forecast?<span className={forecast.trend_percent>=0?"pill good":"pill warn"}>{forecast.trend_percent>=0?"+":""}{Number(forecast.trend_percent).toFixed(1)}% trend · {Number(forecast.confidence).toFixed(0)}% confidence</span>:null}</div>{forecast?<div className="forecastBars">{forecast.points.map(point=><div key={point.date} title={`${point.date}: ${money(point.predicted_revenue_minor,currency)}`}><span style={{height:`${Math.max(5,Math.min(100,(point.predicted_revenue_minor/Math.max(1,...forecast.points.map(p=>p.predicted_revenue_minor)))*100))}%`}}/><small>{point.date.slice(5)}</small></div>)}</div>:<p>Refresh analytics to generate a deterministic moving-average forecast.</p>}</article>
 <article className="adminCard"><div className="cardHead"><div><small>Customer intelligence</small><h2>{totalSegments} segmented</h2></div></div><div className="segmentList">{Object.entries(data?.segment_summary??{}).map(([segment,count])=><div key={segment}><span>{label(segment)}</span><strong>{count}</strong></div>)}{totalSegments===0?<p>No eligible customers yet.</p>:null}</div></article>
 <article className="adminCard wide"><div className="cardHead"><div><small>Explainable insight queue</small><h2>{data?.insights.length??0} active insights</h2></div><span className="pill good">Local deterministic provider</span></div><div className="insightGrid">{data?.insights.map(insight=><article className={`insight ${insight.severity}`} key={insight.id}><div><span className="pill">{insight.type} · {insight.severity}</span><h3>{insight.title}</h3><p>{insight.summary}</p>{insight.recommendations?.map(item=><small key={item}>• {item}</small>)}</div><button disabled={busy} onClick={()=>dismiss(insight)}>Dismiss</button></article>)}{data?.insights.length===0?<p>No active insight requires attention.</p>:null}</div></article>
 <article className="adminCard wide"><div className="cardHead"><div><small>Supplier recommendation layer</small><h2>{data?.supplier_recommendations.length??0} ranked variants</h2></div></div><div className="tableWrap"><table><thead><tr><th>Variant</th><th>Recommended supplier</th><th>Score</th><th>Confidence</th><th>Evidence</th></tr></thead><tbody>{data?.supplier_recommendations.map(item=><tr key={item.id}><td><strong>{item.variant?.name??"Variant"}</strong><small>{item.variant?.sku}</small></td><td><strong>{item.supplier?.name??"Unavailable"}</strong><small>{item.strategy}</small></td><td>{Number(item.score).toFixed(1)}</td><td>{Number(item.confidence).toFixed(0)}%</td><td><small>{item.reason}</small></td></tr>)}{data?.supplier_recommendations.length===0?<tr><td colSpan={5}>No supplier-mapped catalog variant is ready for recommendation.</td></tr>:null}</tbody></table></div></article>
 <article className="adminCard wide"><div className="cardHead"><div><small>Customer segments</small><h2>Top scored customers</h2></div></div><div className="tableWrap"><table><thead><tr><th>Customer</th><th>Segment</th><th>Score</th><th>Orders</th><th>Value</th><th>Recency</th></tr></thead><tbody>{data?.segments.slice(0,25).map(item=><tr key={item.id}><td><strong>{item.user?.name??"Unknown"}</strong><small>{item.user?.email}</small></td><td><span className="pill">{label(item.segment_code)}</span></td><td>{item.score}</td><td>{item.frequency_orders}</td><td>{money(item.monetary_minor,currency)}</td><td>{item.recency_days===null?"No order":`${item.recency_days} days`}</td></tr>)}</tbody></table></div></article>
 </section></>}
 </main>
}
