"use client";
import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
import { PortalHeader } from "@/components/PortalHeader";
import { ApiUser, authApi, errorMessage } from "@/lib/auth-api";
import { Domain, Plan, PluginRecord, saasApi, TenantRecord } from "@/lib/saas-api";
export default function SaasPage(){
 const [user,setUser]=useState<ApiUser|null>(null),[tenant,setTenant]=useState<TenantRecord|null>(null),[plans,setPlans]=useState<Plan[]>([]),[tenants,setTenants]=useState<TenantRecord[]>([]),[plugins,setPlugins]=useState<PluginRecord[]>([]),[domains,setDomains]=useState<Array<Domain&{verification_token?:string|null}>>([]),[platform,setPlatform]=useState(false),[features,setFeatures]=useState<Record<string,unknown>>({}),[usage,setUsage]=useState<Array<{metric:string;quantity:number;limit:number|null;remaining:number|null}>>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const [displayName,setDisplayName]=useState(""),[primary,setPrimary]=useState("#2563eb"),[secondary,setSecondary]=useState("#0f172a"),[supportEmail,setSupportEmail]=useState(""),[domain,setDomain]=useState("");
 const [company,setCompany]=useState(""),[slug,setSlug]=useState(""),[planId,setPlanId]=useState("");
 async function load(){const [me,d,p,ds]=await Promise.all([authApi.me(),saasApi.dashboard(),saasApi.plugins(),saasApi.domains()]);setUser(me.data);setTenant(d.data.current_tenant);setPlans(d.data.plans);setTenants(d.data.tenants);setPlatform(d.data.platform_admin);setFeatures(d.data.entitlements.features);setUsage(d.data.usage);setPlugins(p.data);setDomains(ds.data);const b=d.data.current_tenant.branding;setDisplayName(b?.display_name??d.data.current_tenant.name);setPrimary(b?.primary_color??"#2563eb");setSecondary(b?.secondary_color??"#0f172a");setSupportEmail(b?.support_email??"");if(!planId&&d.data.plans[0])setPlanId(d.data.plans[0].id)}
 useEffect(()=>{load().catch(e=>setError(errorMessage(e)))},[]);
 async function run(action:()=>Promise<unknown>,success:string){setBusy(true);setError("");setMessage("");try{await action();setMessage(success);await load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 function saveBranding(e:FormEvent){e.preventDefault();void run(()=>saasApi.updateBranding({display_name:displayName,primary_color:primary,secondary_color:secondary,support_email:supportEmail||null}),"Branding updated.")}
 function addDomain(e:FormEvent){e.preventDefault();void run(()=>saasApi.addDomain(domain),"Domain added. Copy its verification token, then verify it.");setDomain("")}
 function createTenant(e:FormEvent){e.preventDefault();void run(()=>saasApi.createTenant({name:company,slug,subscription_plan_id:planId,default_currency:"USD",timezone:"UTC"}),"Tenant provisioned.");setCompany("");setSlug("")}
 function install(plugin:PluginRecord){const required=plugin.config_schema.required??[];const configuration:Record<string,string>={};for(const key of required){const value=window.prompt(`Enter ${key}`);if(value===null)return;configuration[key]=value}void run(()=>saasApi.installPlugin(plugin.id,configuration),`${plugin.name} installed.`)}
 if(!user&&!error)return <main className="centerPage"><div className="loader"/><p>Loading SaaS control plane…</p></main>;
 return <main className="portal"><PortalHeader name={user?.name} admin/><section className="shell portalTitle"><p className="eyebrow">Phase 7 · Multi-tenant SaaS & plugins</p><h1>Operate every tenant from one control plane</h1><p>Subscription entitlements, white-label branding, custom domains, quotas and an approved manifest-based plugin marketplace.</p><div className="actions"><Link className="secondary" href="/admin">Identity</Link><Link className="secondary" href="/admin/rules">Rules & fraud</Link><Link className="secondary" href="/admin/suppliers">Suppliers</Link></div></section>{error?<div className="shell notice error">{error}</div>:null}{message?<div className="shell notice success">{message}</div>:null}
 <section className="shell adminLayout"><article className="adminCard"><div className="cardHead"><div><small>Current tenant</small><h2>{tenant?.name}</h2></div><span className="pill good">{tenant?.subscription?.plan??"No plan"}</span></div><form className="formStack compact" onSubmit={saveBranding}><label>Display name<input value={displayName} onChange={e=>setDisplayName(e.target.value)} required/></label><label>Primary color<input value={primary} onChange={e=>setPrimary(e.target.value)} pattern="#[0-9A-Fa-f]{6}"/></label><label>Secondary color<input value={secondary} onChange={e=>setSecondary(e.target.value)} pattern="#[0-9A-Fa-f]{6}"/></label><label>Support email<input type="email" value={supportEmail} onChange={e=>setSupportEmail(e.target.value)}/></label><button className="primary" disabled={busy}>Save branding</button></form></article>
 <article className="adminCard"><div className="cardHead"><div><small>Entitlements</small><h2>Plan capabilities</h2></div></div><div className="roleList">{Object.entries(features).map(([key,value])=><div key={key}><strong>{key}</strong><small>{typeof value==="object"?JSON.stringify(value):String(value)}</small></div>)}</div><div className="roleList">{usage.map(u=><div key={u.metric}><strong>{u.metric}</strong><small>{u.quantity} used · {u.remaining??"Unlimited"} remaining</small></div>)}</div></article>
 <article className="adminCard wide"><div className="cardHead"><div><small>Custom domains</small><h2>{domains.length} domain(s)</h2></div></div><form className="actions" onSubmit={addDomain}><input placeholder="shop.example.com" value={domain} onChange={e=>setDomain(e.target.value)} required/><button disabled={busy}>Add domain</button></form><div className="tableWrap"><table><thead><tr><th>Domain</th><th>Status</th><th>Verification token</th><th>Controls</th></tr></thead><tbody>{domains.map(d=><tr key={d.id}><td><strong>{d.domain}</strong><small>{d.primary?"Primary":"Secondary"}</small></td><td>{d.verified?"Verified":d.status}</td><td><small>{d.verification_token??"—"}</small></td><td><div className="actions">{!d.verified&&d.verification_token?<button onClick={()=>run(()=>saasApi.verifyDomain(d.id,d.verification_token!),"Domain verified.")}>Verify demo</button>:null}{d.verified&&!d.primary?<button onClick={()=>run(()=>saasApi.primaryDomain(d.id),"Primary domain changed.")}>Make primary</button>:null}</div></td></tr>)}</tbody></table></div></article>
 <article className="adminCard wide"><div className="cardHead"><div><small>Approved marketplace</small><h2>{plugins.length} plugins</h2></div><span className="pill">No arbitrary code uploads</span></div><div className="tableWrap"><table><thead><tr><th>Plugin</th><th>Category</th><th>Capabilities</th><th>Status</th><th>Controls</th></tr></thead><tbody>{plugins.map(p=><tr key={p.id}><td><strong>{p.name}</strong><small>{p.slug} · v{p.version}</small></td><td>{p.category}</td><td><small>{p.capabilities.join(", ")}</small></td><td>{p.installation?<span className={p.installation.enabled?"pill good":"pill"}>{p.installation.status}</span>:"Available"}</td><td>{!p.installation?<button disabled={busy} onClick={()=>install(p)}>Install</button>:p.installation.enabled?<button disabled={busy||p.is_core} onClick={()=>run(()=>saasApi.disablePlugin(p.installation!.id),`${p.name} disabled.`)}>Disable</button>:<button disabled={busy} onClick={()=>run(()=>saasApi.enablePlugin(p.installation!.id),`${p.name} enabled.`)}>Enable</button>}</td></tr>)}</tbody></table></div></article>
 {platform?<><article className="adminCard"><div className="cardHead"><div><small>Platform provisioning</small><h2>Create tenant</h2></div></div><form className="formStack compact" onSubmit={createTenant}><label>Company<input value={company} onChange={e=>{setCompany(e.target.value);if(!slug)setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""))}} required/></label><label>Slug<input value={slug} onChange={e=>setSlug(e.target.value)} required/></label><label>Plan<select value={planId} onChange={e=>setPlanId(e.target.value)}>{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className="primary" disabled={busy}>Provision tenant</button></form></article><article className="adminCard wide"><div className="cardHead"><div><small>Tenant registry</small><h2>{tenants.length} tenants</h2></div></div><div className="tableWrap"><table><thead><tr><th>Tenant</th><th>Plan</th><th>Domains</th><th>Status</th></tr></thead><tbody>{tenants.map(t=><tr key={t.id}><td><strong>{t.name}</strong><small>{t.slug}</small></td><td>{t.subscription?.plan??"None"}</td><td><small>{t.domains.map(d=>d.domain).join(", ")||"No domain"}</small></td><td>{t.status}</td></tr>)}</tbody></table></div></article></>:null}</section></main>;
}
