<?php
namespace Modules\Support\Application\Services;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use Modules\Audit\Application\AuditLogger;
use Modules\Notifications\Application\Services\NotificationService;
use Modules\Support\Domain\Enums\TicketPriority;
use Modules\Support\Domain\Enums\TicketStatus;
use Modules\Support\Infrastructure\Models\SupportTicket;
use Modules\Support\Infrastructure\Models\SupportTicketEvent;
use Modules\Support\Infrastructure\Models\SupportTicketMessage;
final class SupportTicketService
{
    public function __construct(private readonly NotificationService $notifications,private readonly AuditLogger $audit){}
    public function create(string $tenantId,User $requester,array $data):SupportTicket{return DB::transaction(function()use($tenantId,$requester,$data){$priority=TicketPriority::from($data['priority']??'normal');$ticket=SupportTicket::query()->create(['tenant_id'=>$tenantId,'requester_id'=>$requester->id,'number'=>'SUP-'.now()->format('ymd').'-'.strtoupper(Str::random(8)),'subject'=>$data['subject'],'category'=>$data['category']??'general','priority'=>$priority,'status'=>TicketStatus::Open,'source'=>'portal','related_type'=>$data['related_type']??null,'related_id'=>$data['related_id']??null,'first_response_due_at'=>now()->addMinutes($priority===TicketPriority::Urgent?30:($priority===TicketPriority::High?120:480)),'resolution_due_at'=>now()->addHours($priority===TicketPriority::Urgent?4:($priority===TicketPriority::High?12:48)),'last_activity_at'=>now()]);SupportTicketMessage::query()->create(['support_ticket_id'=>$ticket->id,'author_id'=>$requester->id,'author_type'=>'customer','body'=>$data['message'],'created_at'=>now()]);SupportTicketEvent::query()->create(['support_ticket_id'=>$ticket->id,'actor_id'=>$requester->id,'event_type'=>'ticket.created','to_value'=>['status'=>'open'],'created_at'=>now()]);$this->audit->record('support.ticket.created',SupportTicket::class,$ticket->id,['number'=>$ticket->number],[],$tenantId,User::class,$requester->id);return $ticket->fresh(['messages','requester']);});}
    public function reply(SupportTicket $ticket,User $author,string $body,bool $internal=false,bool $admin=false):SupportTicket{return DB::transaction(function()use($ticket,$author,$body,$internal,$admin){$locked=SupportTicket::query()->whereKey($ticket->id)->lockForUpdate()->firstOrFail();if(in_array($locked->status,[TicketStatus::Closed],true))throw ValidationException::withMessages(['ticket'=>'Closed tickets cannot receive replies.']);SupportTicketMessage::query()->create(['support_ticket_id'=>$locked->id,'author_id'=>$author->id,'author_type'=>$admin?'agent':'customer','is_internal'=>$internal,'body'=>$body,'created_at'=>now()]);$updates=['last_activity_at'=>now()];if($admin&&!$internal){$updates['first_responded_at']=$locked->first_responded_at??now();$updates['status']=TicketStatus::PendingCustomer;}elseif(!$admin){$updates['status']=TicketStatus::Open;}$locked->forceFill($updates)->save();SupportTicketEvent::query()->create(['support_ticket_id'=>$locked->id,'actor_id'=>$author->id,'event_type'=>'ticket.replied','metadata'=>['internal'=>$internal,'admin'=>$admin],'created_at'=>now()]);if(!$internal){$recipient=$admin?$locked->requester:$locked->assignee;if($recipient)$this->notifications->notify($recipient,$locked->tenant_id,'support.ticket.reply',['ticket_number'=>$locked->number,'subject'=>$locked->subject,'message'=>$body,'action_url'=>$admin?'/support':'/admin/operations'],['in_app','email'],'ticket-reply-'.$locked->id.'-'.now()->timestamp);}return $locked->fresh(['messages','requester','assignee']);});}
    public function transition(SupportTicket $ticket,User $actor,array $data):SupportTicket{return DB::transaction(function()use($ticket,$actor,$data){$locked=SupportTicket::query()->whereKey($ticket->id)->lockForUpdate()->firstOrFail();$from=['status'=>$locked->status->value,'priority'=>$locked->priority->value,'assigned_to'=>$locked->assigned_to];$updates=[];if(isset($data['status'])){$status=TicketStatus::from($data['status']);$updates['status']=$status;if($status===TicketStatus::Resolved)$updates['resolved_at']=now();if($status===TicketStatus::Closed)$updates['closed_at']=now();}if(isset($data['priority']))$updates['priority']=TicketPriority::from($data['priority']);if(array_key_exists('assigned_to',$data))$updates['assigned_to']=$data['assigned_to'];$updates['last_activity_at']=now();$locked->forceFill($updates)->save();SupportTicketEvent::query()->create(['support_ticket_id'=>$locked->id,'actor_id'=>$actor->id,'event_type'=>'ticket.transitioned','from_value'=>$from,'to_value'=>['status'=>$locked->status->value,'priority'=>$locked->priority->value,'assigned_to'=>$locked->assigned_to],'created_at'=>now()]);return $locked->fresh(['messages','requester','assignee']);});}
}
