"use client";

import { useEffect, useState } from "react";
import { apiFetch, ApiEnvelope } from "@/lib/agcp-api";

type Notification = {
  id: number;
  title: string;
  message: string;
  delivered_at?: string | null;
  read_at?: string | null;
};

export default function NotificationsPage() {
  const [rows, setRows] = useState<Notification[]>([]);

  async function load() {
    const result = await apiFetch<ApiEnvelope<Notification[]>>(
      "/api/v1/notifications",
    );

    setRows(result.data);
  }

  useEffect(() => {
    load().catch(() => undefined);
  }, []);

  async function markRead(id: number) {
    await apiFetch(
      `/api/v1/notifications/${id}/read`,
      { method: "POST" },
    );

    await load();
  }

  return (
    <div>
      <div className="page-heading">
        <div>
          <p className="eyebrow">Notifications</p>
          <h2>Notification Center</h2>
          <p>Order and fulfillment updates generated by the outbox pipeline.</p>
        </div>
      </div>

      <div className="notification-list">
        {rows.map((notification) => (
          <article
            className={
              notification.read_at
                ? "notification-card"
                : "notification-card unread"
            }
            key={notification.id}
          >
            <div>
              <h3>{notification.title}</h3>
              <p>{notification.message}</p>
              <small>{notification.delivered_at ?? "Recently"}</small>
            </div>

            {!notification.read_at && (
              <button
                className="small-button"
                onClick={() => markRead(notification.id)}
              >
                Mark read
              </button>
            )}
          </article>
        ))}

        {rows.length === 0 && (
          <div className="empty-state">No notifications yet.</div>
        )}
      </div>
    </div>
  );
}