[program:agcp-staging-next]
command=/usr/bin/npm start -- --hostname 127.0.0.1 --port 3000
directory=/home/agcp/agcp-2026-2027/apps/web
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=agcp
environment=NODE_ENV="production"
redirect_stderr=true
stdout_logfile=/home/agcp/logs/agcp-staging-next.log
stopwaitsecs=60