[program:agcp-staging-queue]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /home/agcp/agcp-2026-2027/apps/backend/artisan queue:work redis --queue=default,external-delivery --sleep=2 --tries=3 --timeout=120
directory=/home/agcp/agcp-2026-2027/apps/backend
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=agcp
numprocs=1
redirect_stderr=true
stdout_logfile=/home/agcp/logs/agcp-staging-queue.log
stopwaitsecs=3600