"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { PortalHeader } from "@/components/PortalHeader";
import { ApiUser, apiFetch, authApi, errorMessage } from "@/lib/auth-api";

type Session={id:string;device:string;platform?:string;browser?:string;ip_address?:string;current:boolean;last_active_at?:string};
type Device={id:string;name:string;platform?:string;browser?:string;last_ip?:string;trusted:boolean;last_seen_at?:string};
type Token={id:string;name:string;abilities:string[];last_used_at?:string;expires_at?:string};
type Passkey={id:number;name:string;last_used_at?:string;created_at?:string};

export default function SecurityPage(){
  const router=useRouter(); const [user,setUser]=useState<ApiUser|null>(null); const [sessions,setSessions]=useState<Session[]>([]); const [devices,setDevices]=useState<Device[]>([]); const [tokens,setTokens]=useState<Token[]>([]); const [passkeys,setPasskeys]=useState<Passkey[]>([]); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [password,setPassword]=useState(""); const [qr,setQr]=useState(""); const [twoCode,setTwoCode]=useState(""); const [recovery,setRecovery]=useState<string[]>([]); const [passkeyName,setPasskeyName]=useState("My device"); const [tokenName,setTokenName]=useState("My API token"); const [plainToken,setPlainToken]=useState("");
  const load=useCallback(async()=>{try{const [me,s,d,t,p]=await Promise.all([authApi.me(),apiFetch<{data:Session[]}>("/api/v1/auth/sessions"),apiFetch<{data:Device[]}>("/api/v1/auth/devices"),apiFetch<{data:Token[]}>("/api/v1/auth/tokens"),apiFetch<{data:Passkey[]}>("/api/v1/auth/passkeys")]);setUser(me.data);setSessions(s.data);setDevices(d.data);setTokens(t.data);setPasskeys(p.data)}catch(e){if((e as {status?:number}).status===401)router.replace("/login");else setError(errorMessage(e))}},[router]);
  useEffect(()=>{void load()},[load]);
  function start(){setBusy(true);setError("");setMessage("")}; function done(){setBusy(false)}
  async function confirmPassword(){if(!password)throw new Error("Enter your current password first.");await apiFetch("/api/v1/auth/user/confirm-password",{method:"POST",body:JSON.stringify({password})})}
  async function enable2fa(){start();try{await apiFetch("/api/v1/auth/user/two-factor-authentication",{method:"POST"});const r=await apiFetch<{svg:string}>("/api/v1/auth/user/two-factor-qr-code");setQr(r.svg);setMessage("Scan the QR code, then enter a generated code to confirm.")}catch(e){setError(errorMessage(e))}finally{done()}}
  async function confirm2fa(e:FormEvent){e.preventDefault();start();try{await apiFetch("/api/v1/auth/user/confirmed-two-factor-authentication",{method:"POST",body:JSON.stringify({code:twoCode})});const codes=await apiFetch<string[]>("/api/v1/auth/user/two-factor-recovery-codes");setRecovery(codes);setQr("");setMessage("Two-factor authentication is enabled. Save the recovery codes securely.");await load()}catch(x){setError(errorMessage(x))}finally{done()}}
  async function disable2fa(){start();try{await confirmPassword();await apiFetch("/api/v1/auth/user/two-factor-authentication",{method:"DELETE"});setRecovery([]);setMessage("Two-factor authentication disabled.");await load()}catch(e){setError(errorMessage(e))}finally{done()}}
  async function registerPasskey(){start();try{await confirmPassword();const {Passkeys}=await import("@laravel/passkeys");await Passkeys.register({name:passkeyName});setMessage("Passkey registered successfully.");await load()}catch(e){setError(errorMessage(e))}finally{done()}}
  async function removePasskey(id:number){start();try{await confirmPassword();await apiFetch(`/api/v1/auth/passkeys/${id}`,{method:"DELETE"});setMessage("Passkey removed.");await load()}catch(e){setError(errorMessage(e))}finally{done()}}
  async function revokeSession(id:string){start();try{await apiFetch(`/api/v1/auth/sessions/${id}`,{method:"DELETE"});setMessage("Session revoked.");await load()}catch(e){setError(errorMessage(e))}finally{done()}}
  async function revokeOthers(){start();try{await apiFetch("/api/v1/auth/sessions/others",{method:"DELETE"});setMessage("All other sessions revoked.");await load()}catch(e){setError(errorMessage(e))}finally{done()}}
  async function trustDevice(id:string){start();try{await confirmPassword();await apiFetch(`/api/v1/auth/devices/${id}/trust`,{method:"POST"});setMessage("Device marked as trusted.");await load()}catch(e){setError(errorMessage(e))}finally{done()}}
  async function removeDevice(id:string){start();try{await apiFetch(`/api/v1/auth/devices/${id}`,{method:"DELETE"});setMessage("Device removed.");await load()}catch(e){setError(errorMessage(e))}finally{done()}}
  async function createToken(e:FormEvent){e.preventDefault();start();setPlainToken("");try{const r=await apiFetch<{data:{token:string}}>("/api/v1/auth/tokens",{method:"POST",body:JSON.stringify({name:tokenName,current_password:password,expires_in_days:30})});setPlainToken(r.data.token);setMessage("API token created. Copy it now.");await load()}catch(x){setError(errorMessage(x))}finally{done()}}
  async function revokeToken(id:string){start();try{await apiFetch(`/api/v1/auth/tokens/${id}`,{method:"DELETE"});setMessage("API token revoked.");await load()}catch(e){setError(errorMessage(e))}finally{done()}}
  if(!user)return <main className="centerPage"><div className="loader"/><p>{error||"Loading security controls…"}</p></main>;
  const admin=user.permissions.includes("identity.admin.access");
  return <main className="portal"><PortalHeader name={user.name} admin={admin}/><section className="shell portalTitle"><p className="eyebrow">Account protection</p><h1>Security center</h1><p>Manage strong authentication, devices, sessions and integration tokens.</p></section>{error?<div className="shell notice error">{error}</div>:null}{message?<div className="shell notice success">{message}</div>:null}<section className="shell securityLayout">
    <article className="securityCard"><div className="cardHead"><div><small>Authentication</small><h2>Two-factor authentication</h2></div><span className={user.two_factor_enabled?"pill good":"pill warn"}>{user.two_factor_enabled?"Enabled":"Required for admin"}</span></div>{!user.two_factor_enabled&&!qr?<button className="primary" disabled={busy} onClick={enable2fa}>Enable authenticator 2FA</button>:null}{qr?<div className="twoFactorSetup"><div className="qr" dangerouslySetInnerHTML={{__html:qr}}/><form className="inlineForm" onSubmit={confirm2fa}><input inputMode="numeric" placeholder="6-digit code" value={twoCode} onChange={(e)=>setTwoCode(e.target.value)}/><button className="primary" disabled={busy}>Confirm</button></form></div>:null}{user.two_factor_enabled?<button className="dangerButton" disabled={busy} onClick={disable2fa}>Disable 2FA</button>:null}{recovery.length?<div className="recovery"><strong>Recovery codes</strong><div>{recovery.map(c=><code key={c}>{c}</code>)}</div></div>:null}</article>
    <article className="securityCard"><div className="cardHead"><div><small>Passwordless</small><h2>Passkeys</h2></div><span className={passkeys.length?"pill good":"pill"}>{passkeys.length?`${passkeys.length} configured`:"Available"}</span></div><p>Register Windows Hello, Touch ID or a compatible security key.</p><div className="inlineForm"><input value={passkeyName} onChange={(e)=>setPasskeyName(e.target.value)} placeholder="Passkey name"/><button className="primary" disabled={busy} onClick={registerPasskey}>Register passkey</button></div><div className="dataList compactList">{passkeys.map(p=><div key={p.id}><div><strong>{p.name}</strong><small>{p.last_used_at?`Last used ${new Date(p.last_used_at).toLocaleString()}`:`Added ${p.created_at?new Date(p.created_at).toLocaleDateString():"recently"}`}</small></div><button className="textButton danger" disabled={busy} onClick={()=>removePasskey(p.id)}>Remove</button></div>)}</div></article>
    <article className="securityCard wide"><div className="cardHead"><div><small>Confirmation</small><h2>Current password</h2></div></div><p>Required before trusting devices, registering passkeys, disabling 2FA or creating tokens.</p><input className="standaloneInput" type="password" autoComplete="current-password" value={password} onChange={(e)=>setPassword(e.target.value)} placeholder="Current password"/></article>
    <article className="securityCard wide"><div className="cardHead"><div><small>Active access</small><h2>Sessions</h2></div><button className="secondary small" onClick={revokeOthers} disabled={busy}>Revoke others</button></div><div className="dataList">{sessions.map(s=><div key={s.id}><div><strong>{s.device}</strong><small>{s.ip_address||"Unknown IP"} · {s.last_active_at?new Date(s.last_active_at).toLocaleString():""}</small></div><span className={s.current?"pill good":"pill"}>{s.current?"Current":"Active"}</span>{!s.current?<button className="textButton danger" onClick={()=>revokeSession(s.id)}>Revoke</button>:null}</div>)}</div></article>
    <article className="securityCard wide"><div className="cardHead"><div><small>Recognized hardware</small><h2>Devices</h2></div></div><div className="dataList">{devices.map(d=><div key={d.id}><div><strong>{d.name}</strong><small>{d.last_ip||"Unknown IP"} · {d.last_seen_at?new Date(d.last_seen_at).toLocaleString():""}</small></div><span className={d.trusted?"pill good":"pill"}>{d.trusted?"Trusted":"Observed"}</span>{!d.trusted?<button className="textButton" onClick={()=>trustDevice(d.id)}>Trust</button>:null}<button className="textButton danger" onClick={()=>removeDevice(d.id)}>Remove</button></div>)}</div></article>
    <article className="securityCard wide"><div className="cardHead"><div><small>Headless integrations</small><h2>API tokens</h2></div></div><form className="inlineForm" onSubmit={createToken}><input value={tokenName} onChange={(e)=>setTokenName(e.target.value)} placeholder="Token name"/><button className="primary" disabled={busy}>Create 30-day token</button></form>{plainToken?<div className="tokenReveal"><strong>Copy now</strong><code>{plainToken}</code></div>:null}<div className="dataList">{tokens.map(t=><div key={t.id}><div><strong>{t.name}</strong><small>Expires {t.expires_at?new Date(t.expires_at).toLocaleDateString():"never"}</small></div><button className="textButton danger" onClick={()=>revokeToken(t.id)}>Revoke</button></div>)}</div></article>
  </section></main>;
}
