"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { PortalHeader } from "@/components/PortalHeader";
import { authApi, ApiUser, errorMessage } from "@/lib/auth-api";
import { Deposit, walletApi } from "@/lib/wallet-api";
export default function DepositsPage(){
 const router=useRouter(); const [user,setUser]=useState<ApiUser|null>(null); const [items,setItems]=useState<Deposit[]>([]); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
 async function load(){const [u,d]=await Promise.all([authApi.me(),walletApi.deposits()]);setUser(u.data);setItems(d.data)}
 useEffect(()=>{load().catch(e=>{if((e as {status?:number}).status===401)router.replace('/login');else setMessage(errorMessage(e))})},[router]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const fd=new FormData(e.currentTarget);try{await walletApi.createDeposit({amount:String(fd.get('amount')),currency:String(fd.get('currency')),method:String(fd.get('method')),external_reference:String(fd.get('reference')||''),customer_note:String(fd.get('note')||'')});e.currentTarget.reset();await load();setMessage('Deposit request submitted for review.')}catch(err){setMessage(errorMessage(err))}finally{setBusy(false)}}
 if(!user)return <main className="centerPage"><div className="loader"/><p>{message||"Loading deposits…"}</p></main>;
 return <main className="portal"><PortalHeader name={user.name} admin={user.permissions.includes('identity.admin.access')}/><section className="shell portalHero"><div><p className="eyebrow">Add balance</p><h1>Submit a deposit request</h1><p>Balance is credited only after an authorized reviewer verifies the payment.</p></div></section>{message?<div className="shell notice success">{message}</div>:null}<section className="shell twoColumn"><form className="formCard" onSubmit={submit}><label>Amount<input name="amount" inputMode="decimal" placeholder="100.00" required pattern="\d+(\.\d{1,2})?"/></label><label>Currency<select name="currency" defaultValue="USD"><option>USD</option><option>BDT</option><option>EUR</option></select></label><label>Method<select name="method" defaultValue="manual"><option value="manual">Manual review</option><option value="bank_transfer">Bank transfer</option><option value="mobile_financial_service">Mobile financial service</option></select></label><label>Payment reference<input name="reference" maxLength={190}/></label><label>Note<textarea name="note" maxLength={2000}/></label><button className="primary" disabled={busy}>{busy?'Submitting…':'Submit deposit'}</button></form><div className="infoCard"><small>Review policy</small><h3>No browser-side balance credit</h3><p>Requests remain pending until the backend posts a balanced journal entry. Duplicate approval attempts are protected by row locking and idempotency controls.</p></div></section><section className="shell actionPanel ledgerPanel"><div><p className="eyebrow">Deposit history</p><h2>Your requests</h2></div><div className="tableWrap"><table><thead><tr><th>Submitted</th><th>Amount</th><th>Method</th><th>Status</th></tr></thead><tbody>{items.length?items.map(d=><tr key={d.id}><td>{d.submitted_at?new Date(d.submitted_at).toLocaleString():"—"}</td><td>{d.amount} {d.currency}</td><td>{d.method.replaceAll('_',' ')}</td><td><span className={`statusPill ${d.status}`}>{d.status}</span></td></tr>):<tr><td colSpan={4}>No deposit requests yet.</td></tr>}</tbody></table></div></section></main>
}
