"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { PortalHeader } from "@/components/PortalHeader";
import { ApiUser, authApi, errorMessage } from "@/lib/auth-api";
import { FraudAssessment, RuleRecord, rulesApi } from "@/lib/rules-api";
export default function RulesAdminPage(){
 const[user,setUser]=useState<ApiUser|null>(null);const[rules,setRules]=useState<RuleRecord[]>([]);const[assessments,setAssessments]=useState<FraudAssessment[]>([]);const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
 const[name,setName]=useState("VIP quantity discount");const[scope,setScope]=useState<"pricing"|"fraud">("pricing");const[field,setField]=useState("pricing.quantity");const[operator,setOperator]=useState("gte");const[value,setValue]=useState("3");const[actionType,setActionType]=useState("discount_percent");const[actionValue,setActionValue]=useState("5");
 async function load(){try{const[u,r,a]=await Promise.all([authApi.me(),rulesApi.rules(),rulesApi.assessments()]);setUser(u.data);setRules(r.data);setAssessments(a.data);}catch(e){setMessage(errorMessage(e));}}
 useEffect(()=>{void load()},[]);
 async function create(event:FormEvent){event.preventDefault();setBusy(true);setMessage("");try{await rulesApi.create({name,scope,priority:100,condition_mode:"all",conditions:[{field,operator,value:Number.isNaN(Number(value))?value:Number(value)}],actions:[{type:actionType,value:Number.isNaN(Number(actionValue))?actionValue:Number(actionValue)}]});setMessage("Draft rule created. Publish it after review.");await load();}catch(e){setMessage(errorMessage(e));}finally{setBusy(false)}}
 async function publish(rule:RuleRecord){setBusy(true);try{await rulesApi.publish(rule.id);setMessage(`${rule.name} published.`);await load();}catch(e){setMessage(errorMessage(e));}finally{setBusy(false)}}
 async function pause(rule:RuleRecord){setBusy(true);try{await rulesApi.pause(rule.id);setMessage(`${rule.name} paused.`);await load();}catch(e){setMessage(errorMessage(e));}finally{setBusy(false)}}
 async function review(item:FraudAssessment,decision:"approve"|"reject"){setBusy(true);try{decision==="approve"?await rulesApi.approve(item.id,"Reviewed in Phase 6 console."):await rulesApi.reject(item.id,"Rejected in Phase 6 console.");setMessage(`Assessment ${decision}d.`);await load();}catch(e){setMessage(errorMessage(e));}finally{setBusy(false)}}
 if(!user&&!message)return <main className="centerPage"><div className="loader"/><p>Loading rule and risk engine…</p></main>;
 return <main className="portal"><PortalHeader name={user?.name} admin/><section className="shell portalTitle"><p className="eyebrow">Phase 6 · Rules, fraud and pricing</p><h1>Decisions without code changes</h1><p>Publish deterministic pricing and risk rules, inspect every execution and release orders held for manual review.</p><div className="actions"><Link className="secondary" href="/admin/suppliers">Supplier engine</Link><Link className="secondary" href="/admin/commerce">Commerce admin</Link></div></section>{message?<div className="shell notice success">{message}</div>:null}
 <section className="shell adminLayout"><article className="adminCard"><div className="cardHead"><div><small>Visual rule builder</small><h2>Create draft</h2></div></div><form className="formStack compact" onSubmit={create}><label>Name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Scope<select value={scope} onChange={e=>{const s=e.target.value as "pricing"|"fraud";setScope(s);if(s==="fraud"){setField("order.total_minor");setActionType("risk_score")}else{setField("pricing.quantity");setActionType("discount_percent")}}}><option value="pricing">Pricing</option><option value="fraud">Fraud</option></select></label><label>Field<input value={field} onChange={e=>setField(e.target.value)} required/></label><label>Operator<select value={operator} onChange={e=>setOperator(e.target.value)}><option>eq</option><option>gte</option><option>gt</option><option>lte</option><option>lt</option><option>in</option></select></label><label>Condition value<input value={value} onChange={e=>setValue(e.target.value)}/></label><label>Action type<input value={actionType} onChange={e=>setActionType(e.target.value)} required/></label><label>Action value<input value={actionValue} onChange={e=>setActionValue(e.target.value)}/></label><button className="primary" disabled={busy}>Create draft</button></form></article>
 <article className="adminCard wide"><div className="cardHead"><div><small>Versioned rules</small><h2>{rules.length} rules</h2></div><span className="pill good">Auditable</span></div><div className="tableWrap"><table><thead><tr><th>Rule</th><th>Scope</th><th>Priority</th><th>Status</th><th>Condition</th><th>Action</th><th>Controls</th></tr></thead><tbody>{rules.map(rule=><tr key={rule.id}><td><strong>{rule.name}</strong><small>{rule.slug} · v{rule.latest_version ?? 1}</small></td><td>{rule.scope}</td><td>{rule.priority}</td><td><span className={rule.status==="active"?"pill good":"pill"}>{rule.status}</span></td><td><small>{JSON.stringify(rule.conditions)}</small></td><td><small>{JSON.stringify(rule.actions)}</small></td><td>{rule.status==="active"?<button disabled={busy} onClick={()=>pause(rule)}>Pause</button>:<button disabled={busy} onClick={()=>publish(rule)}>Publish</button>}</td></tr>)}</tbody></table></div></article>
 <article className="adminCard wide"><div className="cardHead"><div><small>Risk review queue</small><h2>{assessments.filter(a=>a.status==="open").length} open assessments</h2></div></div><div className="tableWrap"><table><thead><tr><th>Customer</th><th>Order</th><th>Score</th><th>Signals</th><th>Status</th><th>Decision</th></tr></thead><tbody>{assessments.length?assessments.map(a=><tr key={a.id}><td><strong>{a.user?.name??"Unknown"}</strong><small>{a.user?.email}</small></td><td>{a.order?<><strong>{a.order.number}</strong><small>{(a.order.total_minor/100).toFixed(2)} {a.order.currency}</small></>:"Checkout attempt"}</td><td><span className={a.score>=60?"pill warn":"pill"}>{a.score} · {a.level}</span></td><td><small>{a.signals.map(s=>`${s.code} +${s.score}`).join(", ")||"No signals"}</small></td><td>{a.status}</td><td>{a.status==="open"&&a.decision==="review"?<div className="actions"><button disabled={busy} onClick={()=>review(a,"approve")}>Approve</button><button disabled={busy} onClick={()=>review(a,"reject")}>Reject</button></div>:a.decision}</td></tr>):<tr><td colSpan={6}>No risk assessments yet.</td></tr>}</tbody></table></div></article></section></main>;
}
