<?php
namespace Modules\Reporting\Application\Services;
use Modules\Reporting\Infrastructure\Models\Invoice;
final class InvoiceDocumentService
{
    public function html(Invoice $invoice):string
    {
        $invoice->loadMissing(['lines','order','user']);$money=fn(int $minor):string=>number_format($minor/100,2).' '.e($invoice->currency);$seller=$invoice->seller_snapshot;$buyer=$invoice->buyer_snapshot;
        $rows='';foreach($invoice->lines as $line){$rows.='<tr><td>'.e($line->description).'</td><td>'.e((string)$line->sku).'</td><td class="n">'.$line->quantity.'</td><td class="n">'.$money($line->unit_price_minor).'</td><td class="n">'.number_format($line->tax_rate_basis_points/100,2).'%</td><td class="n">'.$money($line->tax_minor).'</td><td class="n">'.$money($line->gross_minor).'</td></tr>';}
        return '<!doctype html><html><head><meta charset="utf-8"><title>'.e($invoice->number).'</title><style>body{font:14px Arial;color:#172033;margin:40px}header{display:flex;justify-content:space-between;border-bottom:2px solid #172033;padding-bottom:18px}h1{margin:0}.meta{line-height:1.7}.grid{display:grid;grid-template-columns:1fr 1fr;gap:30px;margin:26px 0}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #ddd;text-align:left}.n{text-align:right}.totals{margin-left:auto;width:360px;margin-top:24px}.totals div{display:flex;justify-content:space-between;padding:6px}.total{font-size:18px;font-weight:bold;border-top:2px solid #172033}.hash{font-size:10px;color:#667085;word-break:break-all;margin-top:35px}@media print{body{margin:15mm}}</style></head><body><header><div><h1>INVOICE</h1><div>'.e((string)($seller['legal_name']??'')).'</div></div><div class="meta"><strong>'.e($invoice->number).'</strong><br>Issued: '.e((string)$invoice->issued_at?->format('Y-m-d')).'<br>Status: '.e($invoice->status->value).'<br>Order: '.e((string)$invoice->order?->number).'</div></header><section class="grid"><div><strong>Seller</strong><br>'.e((string)($seller['legal_name']??'')).'<br>Tax ID: '.e((string)($seller['tax_registration_number']??'—')).'</div><div><strong>Bill to</strong><br>'.e((string)($buyer['name']??'')).'<br>'.e((string)($buyer['email']??'')).'<br>Tax ID: '.e((string)($buyer['tax_identifier']??'—')).'</div></section><table><thead><tr><th>Description</th><th>SKU</th><th class="n">Qty</th><th class="n">Unit</th><th class="n">Tax</th><th class="n">Tax amount</th><th class="n">Gross</th></tr></thead><tbody>'.$rows.'</tbody></table><section class="totals"><div><span>Subtotal</span><span>'.$money($invoice->subtotal_minor).'</span></div><div><span>Discount</span><span>-'.$money($invoice->discount_minor).'</span></div><div><span>Surcharge</span><span>'.$money($invoice->surcharge_minor).'</span></div><div><span>Included tax</span><span>'.$money($invoice->tax_minor).'</span></div><div class="total"><span>Total</span><span>'.$money($invoice->total_minor).'</span></div><div><span>Paid</span><span>'.$money($invoice->amount_paid_minor).'</span></div><div><span>Due</span><span>'.$money($invoice->amount_due_minor).'</span></div></section><p>'.e((string)($seller['footer']??'')).'</p><div class="hash">Document integrity SHA-256: '.e($invoice->content_hash).'</div></body></html>';
    }
}
